// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "vol2birdR_types.h"
#include <RcppGSL.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_vol2bird_namespace__store_main_thread_id
void cpp_vol2bird_namespace__store_main_thread_id();
RcppExport SEXP _vol2birdR_cpp_vol2bird_namespace__store_main_thread_id() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    cpp_vol2bird_namespace__store_main_thread_id();
    return R_NilValue;
END_RCPP
}
// cpp_vol2bird_initialize
void cpp_vol2bird_initialize();
RcppExport SEXP _vol2birdR_cpp_vol2bird_initialize() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    cpp_vol2bird_initialize();
    return R_NilValue;
END_RCPP
}
// cpp_vol2bird_set_wsr88d_site_location
void cpp_vol2bird_set_wsr88d_site_location(std::string loc);
RcppExport SEXP _vol2birdR_cpp_vol2bird_set_wsr88d_site_location(SEXP locSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type loc(locSEXP);
    cpp_vol2bird_set_wsr88d_site_location(loc);
    return R_NilValue;
END_RCPP
}
// cpp_vol2bird_get_wsr88d_site_location
std::string cpp_vol2bird_get_wsr88d_site_location();
RcppExport SEXP _vol2birdR_cpp_vol2bird_get_wsr88d_site_location() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(cpp_vol2bird_get_wsr88d_site_location());
    return rcpp_result_gen;
END_RCPP
}
// cpp_vol2bird_version
std::string cpp_vol2bird_version();
RcppExport SEXP _vol2birdR_cpp_vol2bird_version() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(cpp_vol2bird_version());
    return rcpp_result_gen;
END_RCPP
}
// cpp_mistnet_init
void cpp_mistnet_init(std::string path);
RcppExport SEXP _vol2birdR_cpp_mistnet_init(SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    cpp_mistnet_init(path);
    return R_NilValue;
END_RCPP
}
// cpp_printMemory
void cpp_printMemory();
RcppExport SEXP _vol2birdR_cpp_printMemory() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    cpp_printMemory();
    return R_NilValue;
END_RCPP
}

RcppExport SEXP _rcpp_module_boot_PolarVolume();
RcppExport SEXP _rcpp_module_boot_RaveIO();
RcppExport SEXP _rcpp_module_boot_Vol2BirdConfig();
RcppExport SEXP _rcpp_module_boot_Vol2Bird();

static const R_CallMethodDef CallEntries[] = {
    {"_vol2birdR_cpp_vol2bird_namespace__store_main_thread_id", (DL_FUNC) &_vol2birdR_cpp_vol2bird_namespace__store_main_thread_id, 0},
    {"_vol2birdR_cpp_vol2bird_initialize", (DL_FUNC) &_vol2birdR_cpp_vol2bird_initialize, 0},
    {"_vol2birdR_cpp_vol2bird_set_wsr88d_site_location", (DL_FUNC) &_vol2birdR_cpp_vol2bird_set_wsr88d_site_location, 1},
    {"_vol2birdR_cpp_vol2bird_get_wsr88d_site_location", (DL_FUNC) &_vol2birdR_cpp_vol2bird_get_wsr88d_site_location, 0},
    {"_vol2birdR_cpp_vol2bird_version", (DL_FUNC) &_vol2birdR_cpp_vol2bird_version, 0},
    {"_vol2birdR_cpp_mistnet_init", (DL_FUNC) &_vol2birdR_cpp_mistnet_init, 1},
    {"_vol2birdR_cpp_printMemory", (DL_FUNC) &_vol2birdR_cpp_printMemory, 0},
    {"_rcpp_module_boot_PolarVolume", (DL_FUNC) &_rcpp_module_boot_PolarVolume, 0},
    {"_rcpp_module_boot_RaveIO", (DL_FUNC) &_rcpp_module_boot_RaveIO, 0},
    {"_rcpp_module_boot_Vol2BirdConfig", (DL_FUNC) &_rcpp_module_boot_Vol2BirdConfig, 0},
    {"_rcpp_module_boot_Vol2Bird", (DL_FUNC) &_rcpp_module_boot_Vol2Bird, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_vol2birdR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
