# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export PolarVolume
NULL

#' @export RaveIO
NULL

#' @export Vol2BirdConfig
NULL

#' @export Vol2Bird
NULL

cpp_vol2bird_namespace__store_main_thread_id <- function() {
    invisible(.Call(`_vol2birdR_cpp_vol2bird_namespace__store_main_thread_id`))
}

cpp_vol2bird_initialize <- function() {
    invisible(.Call(`_vol2birdR_cpp_vol2bird_initialize`))
}

cpp_vol2bird_set_wsr88d_site_location <- function(loc) {
    invisible(.Call(`_vol2birdR_cpp_vol2bird_set_wsr88d_site_location`, loc))
}

cpp_vol2bird_get_wsr88d_site_location <- function() {
    .Call(`_vol2birdR_cpp_vol2bird_get_wsr88d_site_location`)
}

cpp_mistnet_init <- function(path) {
    invisible(.Call(`_vol2birdR_cpp_mistnet_init`, path))
}

