# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name PolarVolume
#' @title PolarVolume
#' @description The polar volume object as defined by RAVE.
#' @export PolarVolume
NULL

#' @name RaveIO
#' @title RaveIO routines
#' @description Provides I/O routines using the rave framework
#' @export RaveIO
NULL

#' @name Vol2BirdConfig
#' @title Vol2Bird configuration
#' @description The vol2bird configuration used during processing
#' @export Vol2BirdConfig
NULL

#' @name Vol2Bird
#' @title Vol2Bird
#' @description The vol2bird processing class.
#' Provides methods for processing polar volumes/scans. Typical usage can be
#' processor<-Vol2Bird$new()
#' processor$process(c("/...../volume.h5"),config,"vp.h5","pvol.h5")
#' @export Vol2Bird
NULL

#' Sets the main thread id
#'
cpp_vol2bird_namespace__store_main_thread_id <- function() {
    invisible(.Call(`_vol2birdR_cpp_vol2bird_namespace__store_main_thread_id`))
}

#' Initializes the vol2birdR library
#'
cpp_vol2bird_initialize <- function() {
    invisible(.Call(`_vol2birdR_cpp_vol2bird_initialize`))
}

#' Sets the wsr88d site location file
#'
#' @param loc location of file
cpp_vol2bird_set_wsr88d_site_location <- function(loc) {
    invisible(.Call(`_vol2birdR_cpp_vol2bird_set_wsr88d_site_location`, loc))
}

#' Returns the wsr88d site location file
#'
#' @return location of site location file
cpp_vol2bird_get_wsr88d_site_location <- function() {
    .Call(`_vol2birdR_cpp_vol2bird_get_wsr88d_site_location`)
}

#' Initializes the mistnet shared library pointed to by the path
#'
#' @param path The shared library
cpp_mistnet_init <- function(path) {
    invisible(.Call(`_vol2birdR_cpp_mistnet_init`, path))
}

